#
# Do not change this file. It was generated by 'regs2awk.make.sh'
# from 'regs.awk' and 'cpus/x86_64/regs.list'.
#
# Copyright (C) 2004, 2005 Valery Reznic
# This file is part of the Elf Statifier project
# 
# This project is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License.
# See LICENSE file in the doc directory.

{
	R[$1] = $2; 
}
END {
	for (ind = 0; ind < reg_max; ind++) {
		reg_name = P[ind];
		reg_value = R[reg_name];
		if (reg_value == "") reg_value = "0x0";
		printf("%s:\t.long %s\n", reg_name, reg_value);
	}
}

# Registers List
BEGIN {
	reg_max = 0
	P[reg_max++] = "r15"
	P[reg_max++] = "r14"
	P[reg_max++] = "r13"
	P[reg_max++] = "r12"
	P[reg_max++] = "rbp"
	P[reg_max++] = "rbx"
	P[reg_max++] = "r11"
	P[reg_max++] = "r10"
	P[reg_max++] = "r9"
	P[reg_max++] = "r8"
	P[reg_max++] = "rax"
	P[reg_max++] = "rcx"
	P[reg_max++] = "rdx"
	P[reg_max++] = "rsi"
	P[reg_max++] = "rdi"
	P[reg_max++] = "orig_rax"
	P[reg_max++] = "rip"
	P[reg_max++] = "cs"
	P[reg_max++] = "eflags"
	P[reg_max++] = "rsp"
	P[reg_max++] = "ss"
	P[reg_max++] = "fs_base"
	P[reg_max++] = "gs_base"
	P[reg_max++] = "ds"
	P[reg_max++] = "es"
	P[reg_max++] = "fs"
	P[reg_max++] = "gs"
}
